apiVersion: v1
kind: Service
metadata:
  name: functions 
  namespace: statefun
spec:
  type: ClusterIP
  ports:
    - name: endpoint
      port: 8000
  selector:
    app: statefun
    component: functions 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: functions
  namespace: statefun
spec:
  replicas: 1
  selector:
    matchLabels:
      app: statefun
      component: functions 
  template:
    metadata:
      labels:
        app: statefun
        component: functions 
    spec:
      containers:
        - name: functions 
          image: jungerindy/statefun_train:latest
          #image: train-functions
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
              name: endpoint
          env:
            - name: MONGO_DB_ADDRESS
              value: "mongodb://adminuser:password123@192.168.58.2:32000/"
            - name: DATASET
              value: "FIT"
          livenessProbe:
            tcpSocket:
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 60
          resources:
            requests:
              memory: "5Gi"
              cpu: "1"
            limits:
              memory: "5Gi"
              cpu: "1"

