apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: service-creator-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: service-creator-account
  namespace: default
roleRef:
  kind: Role
  name: service-creator-role
  apiGroup: rbac.authorization.k8s.io
