apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: statefun
  name: service-creator-role
rules:
- apiGroups: [""]
  resources: ["services", "endpoints", "pods","pods/portforward"]
  verbs: ["create", "update", "patch","delete","get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["create", "update","patch","delete","get", "list", "watch"]
- apiGroups: ["flink.apache.org"]  
  resources: ["flinkdeployments"]
  verbs: ["create", "update", "delete", "get", "list", "watch"]
- apiGroups: ["flink.apache.org"]
  resources: ["flinkdeployments/status"]
  verbs: ["get", "list", "watch"] 
