apiVersion: v1
kind: ConfigMap
metadata:
  namespace: statefun
  name: module-config
data:
  module.yaml: |+
    kind: io.statefun.endpoints.v2/http
    spec:
      functions: pred/*
      urlPathTemplate: http://functions.statefun.svc.cluster.local:8000/statefun
    ---
    kind: io.statefun.kafka.v1/ingress
    spec:
      id: pred/in
      address: kafka-cluster-kafka-bootstrap.kafka.svc:9092
      consumerGroupId: my-group-id
      topics:
        - topic: senml-source
          valueType: example/MyMessage
          targets:
            - pred/source
    ---
    kind: io.statefun.kafka.v1/ingress
    spec:
      id: pred/in-2
      address: kafka-cluster-kafka-bootstrap.kafka.svc:9092
      consumerGroupId: my-group-id-2
      topics:
        - topic: pred-sub-task
          valueType: example/MyMessage
          targets:
            - pred/mqttSubscribe

