apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: riot-applications-mongodb
spec:
  members: 3
  type: ReplicaSet
  version: "6.0.5"
  security:
    authentication:
      modes: ["SCRAM"]
  users:
    - name: default
      db: admin
      passwordSecretRef:
        name: default-password
      roles:
        - name: clusterAdmin
          db: admin
        - name: userAdminAnyDatabase
          db: admin
        - name: readWrite
          db: riot-applications
      scramCredentialsSecretName: my-scram
  statefulSet:
      spec:
        volumeClaimTemplates:
        - metadata:
            name: data-volume
          spec:
            accessModes: ["ReadWrite"]
            storageClassName: fast
            resources:
              requests:
                storage: 5Gi
            selector:
              matchLabels:
                type: data
        - metadata:
            name: logs-volume
          spec:
            accessModes: ["ReadWrite"]
            storageClassName: fast
            resources:
              requests:
                storage: 5Gi
            selector:
              matchLabels:
                type: logs


---
apiVersion: v1
kind: Secret
metadata:
  name: default-password
type: Opaque
stringData:
  password: passwd
