apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv
spec:
  accessModes:
  - ReadWrite
  capacity:
    storage: 10Gi
  hostPath:
    path: /data/standard/default/mogodb-pv
    type: ""
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  volumeMode: Filesystem
