apiVersion: v2
name: riot-applications
description: A Helm chart deploying the whole runtime environment needed for the RIoTBench applications.
type: application

version: 0.1.0
appVersion: "0.1.0"

dependencies:
  # - name: flink-kuberntes-operator
  #   repository: https://downloads.apache.org/flink/flink-kubernetes-operator-1.8.0/
  #   version: 1.8.0

  - name: strimzi-kafka-operator
    repository: https://strimzi.io/charts/
    version: "0.41.0"

  - name: kube-prometheus-stack
    repository: https://prometheus-community.github.io/helm-charts/
    version: "58.6.0"
